### ISSUE TITLE
Promise combinators

### ISSUE THREAD

**Issue by avillega** [resonatehq/resonate-sdk-py#45]
## Feature:
Add promise combinators and durable promise combinators (Could be the same) to the sdk.
### List of combinators
- all:
    - input: iterable of invocations
    - output: promise of a list of the fulfillment values
    - throws: if any of the promises throw
- race:
    - input: iterable of invocations
    - output: promise with the eventual state of the first invocation that finishes
- any:
    - input: iterable of invocations
    - output: fulfills when any of the input's invocations fullfils
- all settled:
    - input: iterable of invocations
    - output: promise of a list with the outcome of each of the input's invocations.

**Comment by flossypurse** [comment]
https://github.com/resonatehq/resonate-sdk-py/issues/45
