### ISSUE TITLE
Distributed Coordination Protocol

### ISSUE THREAD

**Issue by Tomperez98** [resonatehq/resonate-sdk-py#54]
**Is your feature request related to a problem? Please describe.**
Implement resume and invoke semantics from server.

Each resonate sdk server is a node in a distributed environment orchestrated by the distributed event loop (the server) who will invoke and resume executions

**Comment by avillega** [comment]
This is a duplicate of https://github.com/resonatehq/resonate-sdk-py/issues/50

**Comment by Tomperez98** [comment]
Closing this in favor of #50
